### ISSUE TITLE
Unexpected Kana from selection

### ISSUE THREAD

**Issue by Naheulf** [cyan-2048/Nihonoari-KaiOS#1] opened 2021-10-20 20:07 UTC
### Description of the Issue

Used kana doesn't match selected kana.
### Steps to Reproduce the Issue

1. Open the app
2. Select Hiragana menu
3. Select the second line (`か き く け こ`)
4. Go back on the main app menu
5. Select `Start` and launch

### Expected Behavior

App should only ask for theses kana: `か` `き` `く` `け` `こ`
### Actual Behavior

App also ask for `が` `ぎ` `ぐ` `げ` `ご`

### Debug Information

Both version available on KaiStore and the latest commit currently available in this repo 63ab6d234d70cb7f820e39622a73cb9e04ffe434.

**Comment by cyan-2048** [comment] 2021-10-20 20:31
Hi, just wanna say thank you so much for using the app, never thought someone would actually use it lmao....

Anyways, that is not unexpected behavior the Android app itself does combine normal kana, dakuten and handakuten... mostly for simplicity i guess... since it isn't that hard to replace the consonant every time you see a specific kana.

I'll think about it....

**Comment by Naheulf** [comment] 2021-10-20 22:20
I said it's unexpected because some kana tables for beginners (like me) does not have dakuten nor handakuten.

**Comment by cyan-2048** [comment] 2022-01-07 15:31
I have decided to rewrite the app and I will be implementing this as an option. Closing this issue once 2.0 is released.

**Closed as completed** 2022-01-23 19:07 UTC
